#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
BasicOmniDrive.c
- Basic driver control program for 2014 VEX omni drive base.
- The left joystick Y-axis controls the robot's forward and backward movement.
- The left joystick X-axis controls the robot's left and right movement.
- The right joystick X-axis controls the robot's rotation.

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        frontRight          VEX Motor 393            Front Right motor
Motor Port 3        backRight           VEX Motor 393            Back Right motor
Motor Port 4        frontLeft           VEX Motor 393            Front Left motor
Motor Port 5        backLeft            VEX Motor 393            Back Left motor
----------------------------------------------------------------------------------------------------*/

task main()
{
  //Loop Forever
  while(true)
  {
    //Remote Control Commands
    motor[frontRight] = - vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch1];
    motor[backRight] = - vexRT[Ch3]  - vexRT[Ch4] + vexRT[Ch1];
    motor[frontLeft] =  vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch1];
	  motor[backLeft] = vexRT[Ch3] - vexRT[Ch4] + vexRT[Ch1];
  }
}
