#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           rightElevator, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftElevator,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
BasicOmniDrive.c
- Basic driver control program for 2014 VEX omni drive base.
- The left joystick Y-axis controls the robot's forward and backward movement.
- The left joystick X-axis controls the robot's left and right movement.
- The right joystick X-axis controls the robot's rotation.
- Button 5 controls the claw.
- Button 6 controls the elevator.

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        frontRight          VEX Motor 393         Front Right motor
Motor Port 3        backRight           VEX Motor 393         Back Right motor
Motor Port 4        frontLeft           VEX Motor 393         Front Left motor
Motor Port 5        backLeft            VEX Motor 393         Back Left motor
Motor Port 6        rightElevator       VEX Motor 393         Right Elevator motor
Motor Port 7        leftElevator        VEX Motor 393         Left Elevator motor
Motor Port 8        claw                VEX Motor 393         Claw motor
----------------------------------------------------------------------------------------------------*/

task main()
{
  //Loop Forever
  while(true)
  {
    //Remote Control Commands
    motor[frontRight] = - vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch1];
    motor[backRight] = - vexRT[Ch3]  - vexRT[Ch4] + vexRT[Ch1];
    motor[frontLeft] =  vexRT[Ch3] - vexRT[Ch4] + vexRT[Ch1];
	  motor[backLeft] = vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch1];

	  //Elevator raise/lower control
	  if (vexRT[Btn6U] == 1) {  // raise elevator when button 6 up pressed
    	motor[rightElevator]  = 127;
    	motor[leftElevator]  = 127;
    } else if (vexRT[Btn6D] == 1) { // lower elevator when button 6 down pressed
    	motor[rightElevator]  = -127;
    	motor[leftElevator]  = -127;
    } else {  // turn motors off when neither button is pressed
      motor[rightElevator] = 0;
      motor[leftElevator] = 0;
    }

    // Claw open/close control
    if (vexRT[Btn5U] == 1) {
    	motor[claw]  = 127;  // close claw
    } else if(vexRT[Btn5D] == 1) {
    	motor[claw]  = -127;  // open claw
    } else {
      motor[claw] = 0; // turn claw motor off
    }
  }
}
