#pragma config(Motor,  port2,           FtRtMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RrRtMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LtRrMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LtFtMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                    - Dual Joystick Control-                                     *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses two joysticks, either right or left (this is configurable below) to drive   *|
|*  the robot.                                                                                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          FtRtMotor           VEX Motor 393          Front Right motor                    *|
|*    Motor - Port 3          RrRtMotor           VEX Motor 393          Rear Right motor
|*    Motor - port 4          LtRrMotor           VEX Motor 393          Rear left motor
|*    Motor - port 5          LtFtMotor           VEX Motor 393          Front left motor
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{

  while(1 == 1)
  {
    motor[LtFtMotor]  = (vexRT[Ch3] + vexRT[Ch1])/2;  // (y + x)/2
    motor[FtRtMotor] = (vexRT[Ch3] - vexRT[Ch1])/2;  // (y - x)/2
    motor[LtRrMotor]  = (vexRT[Ch3] + vexRT[Ch1])/2;  // (y + x)/2
    motor[RrRtMotor] = (vexRT[Ch3] - vexRT[Ch1])/2;  // (y - x)/2
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
